version: '3.8'

services:
  server:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - ./src:/app/src          # Live code sync
      # - ./data:/app/src/data    # SQLite DB persistence
